export declare const Permissions: {
    readonly RESEARCH_VIEW: "research.view";
    readonly RESEARCH_CREATE: "research.create";
    readonly RESEARCH_EDIT: "research.edit";
    readonly RESEARCH_SUBMIT: "research.submit";
    readonly RESEARCH_ARCHIVE: "research.archive";
    readonly RESEARCH_ASSIGN: "research.assign";
    readonly WORKFLOW_VIEW: "workflow.view";
    readonly WORKFLOW_CREATE: "workflow.create";
    readonly WORKFLOW_EDIT: "workflow.edit";
    readonly WORKFLOW_PUBLISH: "workflow.publish";
    readonly FORM_VIEW: "form.view";
    readonly FORM_CREATE: "form.create";
    readonly FORM_EDIT: "form.edit";
    readonly FORM_SUBMIT: "form.submit";
    readonly FORM_APPROVE: "form.approve";
    readonly DOCUMENT_VIEW: "document.view";
    readonly DOCUMENT_UPLOAD: "document.upload";
    readonly DOCUMENT_DOWNLOAD: "document.download";
    readonly DOCUMENT_DELETE: "document.delete";
    readonly EVALUATION_CREATE: "evaluation.create";
    readonly EVALUATION_SUBMIT: "evaluation.submit";
    readonly REB_REVIEW: "reb.review";
    readonly REB_APPROVE: "reb.approve";
    readonly REB_REJECT: "reb.reject";
    readonly REB_REQUEST_REVISION: "reb.request_revision";
    readonly REB_ISSUE_CERTIFICATE: "reb.issue_certificate";
    readonly RPO_ASSIGN: "rpo.assign";
    readonly RPO_MONITOR: "rpo.monitor";
    readonly RPO_REPORT: "rpo.report";
    readonly VPAA_VIEW: "vpaa.view";
    readonly VPAA_APPROVE: "vpaa.approve";
    readonly USER_MANAGE: "user.manage";
    readonly ROLE_MANAGE: "role.manage";
    readonly SYSTEM_CONFIGURE: "system.configure";
    readonly AUDIT_VIEW: "audit.view";
    readonly DASHBOARD_CONFIGURE: "dashboard.configure";
};
export type Permission = (typeof Permissions)[keyof typeof Permissions];
export declare const ALL_PERMISSIONS: ("research.view" | "research.create" | "research.edit" | "research.submit" | "research.archive" | "research.assign" | "workflow.view" | "workflow.create" | "workflow.edit" | "workflow.publish" | "form.view" | "form.create" | "form.edit" | "form.submit" | "form.approve" | "document.view" | "document.upload" | "document.download" | "document.delete" | "evaluation.create" | "evaluation.submit" | "reb.review" | "reb.approve" | "reb.reject" | "reb.request_revision" | "reb.issue_certificate" | "rpo.assign" | "rpo.monitor" | "rpo.report" | "vpaa.view" | "vpaa.approve" | "user.manage" | "role.manage" | "system.configure" | "audit.view" | "dashboard.configure")[];
//# sourceMappingURL=permissions.d.ts.map